### PR TITLE
Add musicxml parser

### PR DESCRIPTION
**Pull request by hanshoglund**
By @jmorag from https://github.com/hanshoglund/music-suite/pull/22

### CODE REVIEW

**Comment by jmorag** [comment]
Just tried pushing here but was rejected. Do I not have repository access?

**Comment by hanshoglund** [comment]
@jmorag Should work now!

**Comment by jmorag** [comment]
Looks like everything passes now. You were right about the unicode issue @hanshoglund

**Comment by hanshoglund** [comment]
Thanks, merged!

**Pull request merged**
